### ISSUE TITLE
Discourse Schema Change

### ISSUE THREAD

**Issue by mbillow** [sman591/discourse-nntp-bridge#28]
```
Job exception: PG::UndefinedColumn: ERROR:  column users.email does not exist
LINE 1: SELECT  "users".* FROM "users" WHERE "users"."email" = '[redacted]'...
                                             ^
: SELECT  "users".* FROM "users" WHERE "users"."email" = '[redacted]'  ORDER BY "users"."id" ASC LIMIT 1
```

The Discourse schema has changed from storing the email address of the user in the `users` table to having a `users_emails` table with foreign keys relating email addresses back to the user.

**Comment by sman591** [comment]
It was only a matter of time... I'll look into it

Are all imports currently failing?
